### ISSUE TITLE
Error trying to import custom made .dat files.

### ISSUE THREAD

**Issue by RangaBricks** [cuddlyogre/ExportLDraw#29]
Hello there,
I've created new minifig arms which have higher polycounts but I'm struggling to get them imported into Blender as the plugin keeps throwing an error. Usually custom parts off Ldraw or elsewhere are fine, but something is throwing this off.

The arms were created via Studio Parts designer

In my test file there's a left and right arm, but one arm fails to import, even if I redo the file from scratch.
I can import each arm separately, but while it works it still throws an error (see below).
To make matters more confusing I've tried the old TonyLobster plugin and it imports fine.

Below is the error code.

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ExportLDraw-2022-08-13-01\operator_import.py", line 326, in execute
    blender_import.do_import(bpy.path.abspath(self.filepath))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ExportLDraw-2022-08-13-01\blender_import.py", line 42, in do_import
    obj = root_node.load()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ExportLDraw-2022-08-13-01\ldraw_node.py", line 199, in load
    child_node.load(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ExportLDraw-2022-08-13-01\ldraw_node.py", line 272, in load
    ldraw_props.set_props(obj, self.file, color_code)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ExportLDraw-2022-08-13-01\ldraw_props.py", line 15, in set_props
    obj.ldraw_props.license = ldraw_file.license
TypeError: bpy_struct: item.attr = val: LDrawProps.license doesn't support None from string types

Attached is a zip file that has the .dat files and Left/Right/Both arms.

[arms.zip](https://github.com/cuddlyogre/ExportLDraw/files/9612227/arms.zip)

**Comment by cuddlyogre** [comment]
Fixed. The error was due to not handling the file license being missing.

https://github.com/cuddlyogre/ExportLDraw/releases/tag/2022-09-21-00
