### ISSUE TITLE
API support?

### ISSUE THREAD

**Issue by AllanJard** [cuddlyogre/ExportLDraw#36]
Is there any chance that it might be possible to import an ldraw .dat file via the Python API for Blender. The built in importers have [their own API methods](https://docs.blender.org/api/current/bpy.ops.import_scene.html), and I'm just wondering if it would be possible to expose such an API for this plug-in? I'm looking to be able to use the Python API of Blender to generate some Lego part renders.

**Comment by cuddlyogre** [comment]
Are you asking if it's possible to import just part files? If so, that's already possible. The process is the same as importing a model. 

If you're looking to do it programmatically outside of the normal import process, I'm sure it's possible, I'd just need to know what kind of interface you'd like to see. 

Or are you asking of I can add a function to download missing files from the part library? If so, I have something like that for my own use that I hesitate to release because it has the potential to DDOS the LDraw website.

**Comment by AllanJard** [comment]
Yes, just the part files. What's the Python API for the import? I couldn't see anything about it in the readme.

**Comment by cuddlyogre** [comment]
There's no specific API for working with the importer outside of the import/export menus, but I can build one I suppose. But I'm not sure if Blender supports calling methods of a plugin from another plugin or the script editor. I'll have to look into it.

**Comment by brianlow** [comment]
The existing extension is available to Blender's Python API... I got partially there:

```python
# test.py

import bpy
import os
import math

# don't remember what this is for
bpy.ops.wm.read_factory_settings(use_empty=True)

bpy.ops.preferences.addon_install(filepath="/Users/brian/Downloads/ExportLDraw-2023-05-17-00.zip")

# Fails with missing file otherwise
with open('/Users/brian/Library/Application Support/Blender/3.5/scripts/addons/ExportLDraw-2023-05-17-00/config/ImportOptions.json', "w") as f:
    f.write('{}')

bpy.ops.preferences.addon_enable(module="ExportLDraw-2023-05-17-00")

# might need to restart the script here

# Import
# See the options here:
# https://github.com/cuddlyogre/ExportLDraw/blob/2da11cde59ee69d113324edc4241a92272deeb48/operator_import.py#L12
bpy.ops.ldraw_exporter.import_operator(**{
    "filepath": "/Users/brian/dev/lego-rendering/ldraw/parts/3001.dat",
    "ldraw_path": "/Users/brian/dev/lego-rendering/ldraw/",
    "display_logo": True,
})

# Create a new camera object
bpy.ops.object.camera_add(location=(0, 0, 2))
camera = bpy.context.object
bpy.context.scene.camera = camera

# TODO: need to add a light

# Render
bpy.context.scene.render.filepath = os.path.abspath("./renders/test.png")
bpy.ops.render.render(write_still=True)

# Save a .blend file so we can open in Blender and troubleshoot the scene
bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath("./renders/test.blend"))

```

run with

```bash
/Applications/Blender.app/Contents/MacOS/Blender --background --python test.py
```

Any idea why it is looking for `s\3001s01.dat` when I am trying to load `3001.dat`? I see these in the console:

```
missing LDCfgalt.ldr
missing LDConfig.ldr
missing s\3001s01.dat
unpack requires a buffer of 3 bytes
Bad color code: 16
```

Using the same paths work when importing using Blender -> File -> Import

**Comment by cuddlyogre** [comment]
That's a sign you haven't set your LDraw paths. 

s\3001s01.dat is a subpart. The color is also not loading. If you look in filesystem.py you can see the logic for building paths. 

When I get to my computer, I'll share a code snippet that will help.

**Comment by cuddlyogre** [comment]
```
from .filesystem import FileSystem 

FileSystem.ldraw_path = FileSystem.locate_ldraw()
FileSystem.studio_ldraw_path = FileSystem.locate_studio_ldraw()
FileSystem.build_search_paths()
```

Put this before you start your import.

**Comment by brianlow** [comment]
Success! 

<img width="603" alt="image" src="https://github.com/cuddlyogre/ExportLDraw/assets/938138/de6372ea-2f87-4baa-8d24-33c787562d85">


I wasn't sure how to import the `FileSystem` class since it doesn't live in `.filesystem` in the Blender Python environment. I did discover you need to install the add-on, quit Blender and then render.

```python
# one time setup

import bpy
import os

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.preferences.addon_install(filepath="/Users/brian/Downloads/ExportLDraw-2023-05-17-00.zip")
# Fails with missing file otherwise
with open('/Users/brian/Library/Application Support/Blender/3.5/scripts/addons/ExportLDraw-2023-05-17-00/config/ImportOptions.json', "w") as f:
   f.write('{}')
bpy.ops.preferences.addon_enable(module="ExportLDraw-2023-05-17-00")
```
then
```python
import bpy
import os

# Clear the scene (i.e. the cube that is added by default)
bpy.ops.object.select_all(action='DESELECT')
for obj in bpy.context.scene.objects:
    if obj.type not in {'LIGHT', 'CAMERA'}:
        obj.select_set(True)
bpy.ops.object.delete()


# Import
# See the options here:
# https://github.com/cuddlyogre/ExportLDraw/blob/2da11cde59ee69d113324edc4241a92272deeb48/operator_import.py#L12
bpy.ops.ldraw_exporter.import_operator(**{
    "filepath": "/Users/brian/dev/lego-rendering/ldraw/parts/3001.dat",
    "ldraw_path": "/Users/brian/dev/lego-rendering/ldraw/",
    "display_logo": False,
    "import_edges": False,
    "use_freestyle_edges": False,
})

# Render
bpy.context.scene.render.filepath = os.path.abspath("./renders/test.png")
bpy.ops.render.render(write_still=True)

# Save a .blend file so we can open in Blender and troubleshoot the scene
bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath("./renders/test.blend"))
```

**Comment by cuddlyogre** [comment]
Nice. I'm glad you got it working.

**Comment by AllanJard** [comment]
I'm not having any lunch I'm afraid. I'm not sure what I'm messing.

I've created `once.py` for the setup:

```python
import bpy
import os

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.preferences.addon_install(filepath="/home/allan/Downloads/ExportLDraw-master.zip")
# Fails with missing file otherwise
with open('/home/allan/.config/blender/3.5/scripts/addons/ExportLDraw-master/config/ImportOptions.json', "w") as f:
   f.write('{}')
bpy.ops.preferences.addon_enable(module="ExportLDraw-master")
```

It appears to run okay:

```
> python3 once.py
reloading addon: ExportLDraw-master 1684690033.0671883 1684690586.8446846 '/home/allan/.config/blender/3.5/scripts/addons/ExportLDraw-master/__init__.py'
Modules Installed () from '/home/allan/Downloads/ExportLDraw-master.zip' into '/home/allan/.config/blender/3.5/scripts/addons'
Info: Modules Installed () from '/home/allan/Downloads/ExportLDraw-master.zip' into '/home/allan/.config/blender/3.5/scripts/addons'
Error: Not freed memory blocks: 24293, total unfreed memory 8.026337 MB
```

Then an `import-test.py`:

```python
import bpy
import os

# Clear the scene (i.e. the cube that is added by default)
bpy.ops.object.select_all(action='DESELECT')
for obj in bpy.context.scene.objects:
    if obj.type not in {'LIGHT', 'CAMERA'}:
        obj.select_set(True)
bpy.ops.object.delete()


# Import
# See the options here:
# https://github.com/cuddlyogre/ExportLDraw/blob/2da11cde59ee69d113324edc4241a92272deeb48/operator_import.py#L12
bpy.ops.ldraw_exporter.import_operator(**{
    "filepath": "/home/allan/ldraw/parts/3001.dat",
    "ldraw_path": "/home/allan/ldraw/",
    "display_logo": False,
    "import_edges": False,
    "use_freestyle_edges": False,
})

# Render
bpy.context.scene.render.filepath = os.path.abspath("./renders/test.png")
bpy.ops.render.render(write_still=True)

# Save a .blend file so we can open in Blender and troubleshoot the scene
bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath("./renders/test.blend"))
```

Results in an error:

```
> python3 import-test.py
Traceback (most recent call last):
  File "/home/allan/ldraw/import-test.py", line 15, in <module>
    bpy.ops.ldraw_exporter.import_operator(**{
  File "/usr/lib64/python3.10/site-packages/bpy/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.ldraw_exporter.import_operator" error, could not be found
```

Any ideas what I've done wrong / not done?

**Comment by brianlow** [comment]
Not sure. It seems like the add-on isn't installed or enabled. In import-test.py (and maybe at the end of once.py):
```
for addon in bpy.context.preferences.addons:
    print(addon.module)
```

and look for `io_scene_importldraw`. 

Some random ideas
- install the add-on in the Blender UI (maybe it will carry over to the Blender Python env)
- combine the once.py and test-setup.py (maybe the add-on isn't remembered between Blender Python sessions)

**Comment by AllanJard** [comment]
That's done it. Wicked - thanks so much for your help with this and he plugin in general! Going to close as it does appear to be fully working with the Blender API already :)
