### ISSUE TITLE
cant import files in blender 

### ISSUE THREAD

**Issue by MAriehamn360-Vitrin2** [cuddlyogre/ExportLDraw#52]
when i import a model i made i get this error 
Python: Traceback (most recent call last):
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\operator_import.py", line 363, in execute
    blender_import.do_import(bpy.path.abspath(self.filepath))
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\blender_import.py", line 49, in do_import
    obj = root_node.load(color_code=color_code, return_mesh=return_mesh)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_node.py", line 180, in load
    child_node.load(
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_node.py", line 180, in load
    child_node.load(
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_node.py", line 284, in load
    mesh = ldraw_mesh.create_mesh(key, geometry_data, color_code, return_mesh=return_mesh)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 21, in create_mesh
    __process_bmesh(mesh, geometry_data, color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 62, in __process_bmesh
    bm = __process_bmesh_faces(mesh, geometry_data, color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 134, in __process_bmesh_faces
    material = BlenderMaterials.get_material(
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\blender_materials.py", line 49, in get_material
    color = LDrawColor.get_color(color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_color.py", line 274, in get_color
    return cls.__colors[color_code]
KeyError: '1009023'

it appears to be part missing but the model is built with parts made in bricklink studio and i also conected the addon to Ldraw map both for bricklink studio parts and for Ldraw parts. 

here are images 
![Screenshot 2024-02-27 011810](https://github.com/cuddlyogre/ExportLDraw/assets/156545899/3c71f7f6-897d-4f7e-aa34-4ac4d5a113a3)
![Screenshot 2024-02-27 011834](https://github.com/cuddlyogre/ExportLDraw/assets/156545899/59c0f1f0-647a-4452-a961-a21ddd247233)

**Comment by cuddlyogre** [comment]
Could you link to the model so I can troubleshoot? It's having trouble with that color code.

**Comment by MAriehamn360-Vitrin2** [comment]
i dint know how to send ldraw via github

**Comment by MAriehamn360-Vitrin2** [comment]
Here is a download link to my model i tried to import in blender 
https://drive.google.com/file/d/1jFGZrSzDZI8K-hKj8qRk8G0tTgsyAwc3/view?usp=sharing

**Comment by MAriehamn360-Vitrin2** [comment]
i tried with a fresh re install of windows but still gets error like this 

Python: Traceback (most recent call last):
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\operator_import.py", line 363, in execute
    blender_import.do_import(bpy.path.abspath(self.filepath))
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\blender_import.py", line 49, in do_import
    obj = root_node.load(color_code=color_code, return_mesh=return_mesh)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_node.py", line 180, in load
    child_node.load(
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_node.py", line 284, in load
    mesh = ldraw_mesh.create_mesh(key, geometry_data, color_code, return_mesh=return_mesh)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 21, in create_mesh
    __process_bmesh(mesh, geometry_data, color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 62, in __process_bmesh
    bm = __process_bmesh_faces(mesh, geometry_data, color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_mesh.py", line 134, in __process_bmesh_faces
    material = BlenderMaterials.get_material(
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\blender_materials.py", line 49, in get_material
    color = LDrawColor.get_color(color_code)
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ExportLDraw-2024-01-22-00\ldraw_color.py", line 274, in get_color
    return cls.__colors[color_code]
KeyError: '1009022'

**Comment by cuddlyogre** [comment]
The color code you are having trouble with is Luminous Amber, which is a custom Stud.io color. I would like to support it, but I couldn't find any connection between the color code 1009022 and Luminous Amber. I couldn't even find anything on the internet about these custom color codes. That means I will have to treat it as invalid, which turns it red so it's easier to find.

This release fixes the error
https://github.com/cuddlyogre/ExportLDraw/releases/tag/2024-03-02-00

**Comment by MAriehamn360-Vitrin2** [comment]
thank you so much :) it worked
