### ISSUE TITLE
import error in latest blender version

### ISSUE THREAD

**Issue by Archviz360** [cuddlyogre/ExportLDraw#62]
im getting this error  when i try to import in blender 4.3

Python: Traceback (most recent call last):
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\ExportLDraw-2024-09-12-00\operator_import.py", line 369, in execute
    blender_import.do_import(bpy.path.abspath(self.filepath))
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\ExportLDraw-2024-09-12-00\blender_import.py", line 36, in do_import
    __scene_setup()
  File "C:\Users\dacia\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\ExportLDraw-2024-09-12-00\blender_import.py", line 88, in __scene_setup
    bpy.context.scene.eevee.use_ssr = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SceneEEVEE' object has no attribute 'use_ssr'

**Comment by cuddlyogre** [comment]
This release corrects the issue.
https://github.com/cuddlyogre/ExportLDraw/releases/tag/2024-11-29-00
